apiVersion : apps/v1
kind: Deployment
metadata:
  name: "jenkins"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "jenkins-app"
  template:
    metadata:
      labels:
        app: "jenkins-app"
    spec:
      containers:
        - name: "jenkins"
          image: "vssrepos.azurecr.io/vss"
          ports:
          - containerPort: 8080