apiVersion: v1
kind: Service
metadata:
    name: "vss-fc8a"
    labels:
        app: "vss-fc8a"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "vss-fc8a"